---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: devops-tool-fontend-svc
    namespace: devops-tool
    labels:
      app: devops-tool-fontend
  spec:
    selector:
      app: devops-tool-fontend
    ports:
    - name: tool-port
      port: 4200
      targetPort: 5000
      nodePort: 31000
      protocol: TCP
    type: NodePort
    
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: devops-tool-fontend
    namespace: devops-tool
    labels:
      app: devops-tool-fontend
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: devops-tool-fontend
    template:
      metadata:
        labels:
          app: devops-tool-fontend
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - devops-tool
                topologyKey: kubernetes.io/hostname
              weight: 100
        containers:
        - image: 172.17.162.231/platform-tool/fontend:v1.0.3
          name: fontend
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: tool-port
          resources:
            limits:
              memory: 4Gi
              cpu: 4
            requests:
              memory: 128Mi
              cpu: 10m
          env:
          - name: WEBAPI__SERVER
            value: '172.17.206.81:32538'
kind: List
